"""
WAF Detection Module
Detects presence and type of Web Application Firewall.
Learned from: XSStrike (66 WAF signatures — best WAF detection anywhere)
"""

from __future__ import annotations
import re
from typing import List, Optional, Tuple
from webshield.core.models import Finding, Severity
from webshield.core.http import get_client

# Signature: (page_pattern, code_pattern, headers_pattern)
# Scoring: page match = 1pt, code match = 0.5pt, headers match = 1pt
WAF_SIGNATURES = {
    "Cloudflare": {
        "page":    r"cloudflare|cf-ray|__cfduid|attention required|cloudflare ray id",
        "code":    r"403|429|503",
        "headers": r"cf-ray|server: cloudflare",
    },
    "AWS WAF": {
        "page":    r"aws.*waf|request blocked",
        "code":    r"403",
        "headers": r"x-amzn-requestid|x-amz-cf-id|x-amz-id",
    },
    "Akamai": {
        "page":    r"akamai|reference #[0-9\.]+ error|the requested url was rejected",
        "code":    r"403",
        "headers": r"akamai|x-akamai",
    },
    "Sucuri": {
        "page":    r"sucuri website firewall|access denied|blocked by sucuri",
        "code":    r"403|409",
        "headers": r"x-sucuri-id|x-sucuri-cache|server: sucuri",
    },
    "ModSecurity": {
        "page":    r"mod_security|modsecurity|not acceptable|this error was generated by mod_security",
        "code":    r"406|501",
        "headers": r"mod_security|modsec",
    },
    "F5 BIG-IP ASM": {
        "page":    r"the requested url was rejected|f5 networks|big-ip",
        "code":    r"403",
        "headers": r"x-cnection|bigipserver|x-wa-info",
    },
    "Incapsula": {
        "page":    r"incapsula incident|powered by incapsula",
        "code":    r"403",
        "headers": r"x-iinfo|x-cdn=incapsula",
    },
    "Imperva": {
        "page":    r"imperva|incapsula",
        "code":    r"403",
        "headers": r"x-iinfo",
    },
    "Barracuda": {
        "page":    r"barracuda networks|you have been blocked",
        "code":    r"403",
        "headers": r"barracuda",
    },
    "Fortinet FortiWeb": {
        "page":    r"fortiweb|fortigate|application firewall",
        "code":    r"403",
        "headers": r"fortigate|fortiweb",
    },
    "Wordfence": {
        "page":    r"wordfence|generated by wordfence|your access to this site has been limited",
        "code":    r"403",
        "headers": r"",
    },
    "Nginx WAF": {
        "page":    r"nginx.*block|blocked by nginx",
        "code":    r"444",
        "headers": r"x-nginx-cache.*BLOCK",
    },
    "Cloudfront": {
        "page":    r"request blocked|generated by cloudfront",
        "code":    r"403",
        "headers": r"x-amz-cf-id|via:.*cloudfront",
    },
    "Reblaze": {
        "page":    r"reblaze",
        "code":    r"403",
        "headers": r"x-rb-|rbzid",
    },
    "Wallarm": {
        "page":    r"wallarm",
        "code":    r"403",
        "headers": r"x-wallarm",
    },
    "NAXSI": {
        "page":    r"naxsi|nginx|this request has been blocked",
        "code":    r"400",
        "headers": r"x-data-origin",
    },
}

# Noisy probe payload to trigger WAF
PROBE_PAYLOAD = "/?q=<script>alert(1)</script>&id=1+UNION+SELECT+1,2,3--"


def _detect_waf(page: str, code: str, headers: str) -> Optional[Tuple[str, float]]:
    best_match = (None, 0.0)
    for waf_name, sigs in WAF_SIGNATURES.items():
        score = 0.0
        if sigs["page"] and re.search(sigs["page"], page, re.IGNORECASE):
            score += 1.0
        if sigs["code"] and re.search(sigs["code"], code, re.IGNORECASE):
            score += 0.5
        if sigs["headers"] and re.search(sigs["headers"], headers, re.IGNORECASE):
            score += 1.0
        if score > best_match[1]:
            best_match = (waf_name, score)
    # Require score >= 1.0 to avoid false positives from partial header matches alone
    return best_match if best_match[0] and best_match[1] >= 1.0 else None


def scan(url: str, timeout: float = 10.0) -> List[Finding]:
    findings: List[Finding] = []
    probe_url = url.rstrip("/") + PROBE_PAYLOAD

    try:
        with get_client(timeout=timeout) as client:
            resp = client.get(probe_url)

        page    = resp.text
        code    = str(resp.status_code)
        headers = str(dict(resp.headers)).lower()

        result = _detect_waf(page, code, headers)

        if result:
            waf_name, score = result
            findings.append(Finding(
                title=f"WAF Detected: {waf_name}",
                severity=Severity.INFO,
                description=(
                    f"A Web Application Firewall ({waf_name}) was detected protecting this site. "
                    f"Detection confidence score: {score:.1f}/2.5. "
                    "WAFs add a layer of protection but are not a substitute for secure code."
                ),
                evidence=(
                    f"Probe URL: {probe_url}\n"
                    f"HTTP Status: {code}\n"
                    f"WAF: {waf_name} (confidence: {score:.1f})"
                ),
                remediation=(
                    "WAFs are a good defense-in-depth layer. Ensure your WAF rules are "
                    "up to date and that you are not relying solely on WAF for security."
                ),
                reference="https://owasp.org/www-community/Web_Application_Firewall",
            ))
        else:
            findings.append(Finding(
                title="No WAF Detected",
                severity=Severity.INFO,
                description=(
                    "No Web Application Firewall was detected. Consider adding a WAF "
                    "for additional defense-in-depth protection. Options include Cloudflare "
                    "(free tier), AWS WAF, or ModSecurity on your server."
                ),
                evidence=f"Probe returned HTTP {code} with no WAF signatures",
                remediation="Consider deploying Cloudflare (free), AWS WAF, or ModSecurity.",
                reference="https://owasp.org/www-community/Web_Application_Firewall",
            ))

    except Exception as e:
        findings.append(Finding(
            title="WAF Detection Failed",
            severity=Severity.INFO,
            description=f"Could not probe for WAF: {e}",
        ))

    return findings
